---
title: "init_strata_summaries"
author: "Shelby Sundquist"
date: "2022-12-16"
output: html_document
---

```{r}
library(pdftools)
library(terra)
library(data.table)
library(stringr)
library(dplyr)
library(tibble)

Dir = ""
setwd(Dir)
tempDir = "intermediate_data/"
```

Extracting data from TVSF inventory pdf
```{r}
#Copied from script pdfAppandixB_InvData.R

pdf = pdf_data("http://forestry.alaska.gov/Assets/pdfs/forestinventories/tvsf_inventory_2013.pdf")
# This data can also be found in the raw folder


data = list()
table = data.frame(species = character(), size = double(), count = double())
for(i in 1:16) {
  data[[i]] <- table
}

# extract data from pdf
  
raw = pdf[[81]]
raw$page = 81
pages = 82:124 #pg 107 is start of volume 2
#Volume 1 is Katishna, Fairbanks, Delta. Volume 2 is Tok Management Area (less productive)

for(i in pages) {
  pdf[[i]]$page = i
  raw = rbind(raw, pdf[[i]])
}
raw = as.data.frame(raw)
raw = raw[order(raw$page, raw$y, raw$x),]
raw$y = raw$y+1000*raw$page

spec = c("Aspen","Balsam","Birch","Black","White")
kw = c("Stratum",spec)
burn = raw
burn$row = 1:nrow(burn)
key = burn[burn$text %in% kw & burn$x < 100,]
while(nrow(key>0)) {
  burn$row = 1:nrow(burn)
  key = burn[burn$text %in% kw & burn$x < 100,]
  if(nrow(key) == 0) {break}
  if(key$text[1] == "Stratum") {
    stratum = as.integer(burn$text[key$row[1]+1])
  } else {
    sp = key$text[1]
    start = key$y[1]
    end = burn[burn$text == "Sum" & burn$y > start,]$y[1]
    box = burn[burn$y > start & burn$y < end,]
    while(nrow(box)>0) {
      y1 = min(box$y)
      size = box$text[1]
      count = box$text[2]
      box = box[box$y != y1,]
      data[[stratum]] = rbind(data[[stratum]], c(sp, as.double(size), as.double(count)))
    }
    
  }
  burn = burn[-(1:(key$row[1])),]
}

#NA's seem to go into stored data at page breaks; will just omit
data = na.omit(data)
for(i in 1:16) {
  colnames(data[[i]]) = c("species","dbh_in","count_acre")
}


saveRDS(data, paste0(tempDir, "Inventory_AppB_StemCount_Vol1.RData"))
```

```{r}
#Adapted from init_inputs.R

#Starting with volume 1
strata = readRDS(paste0(tempDir, "Inventory_AppB_StemCount_Vol1.RData"))
acre_to_ha = 2.471
in_to_cm = 2.54
numspec = 10
numbins = 10

#Create init_sp dataframe
init_sp = as.data.frame(1); colnames(init_sp) = c("stratum")
init_sp$totstems = -1
init_sp$ALNUsinu = 0
init_sp$ALNUtenu = 0
init_sp$BETUneoa = 0
init_sp$LARIlari = 0
init_sp$PICEglau = 0
init_sp$PICEmari = 0
init_sp$POPUbals = 0
init_sp$POPUtrem = 0
init_sp$SALIplan = 0
init_sp$SALIscou = 0
#Create init_dbh dataframe
init_dbh = as.data.frame(1); colnames(init_dbh) = c("stratum")
spec = c("ALNUsinu","ALNUtenu","BETUneoa","LARIlari","PICEglau","PICEmari","POPUbals","POPUtrem","SALIplan","SALIscou")
size = c("less5","5to10","10to20","20to30","30to40","40to50","50to60","60to70","70to80","80up")
cols = c()
for(i in 1:numspec) {
  for(j in 1:numbins) {
    cols = c(cols, paste0(spec[i],"_",size[j]))
    init_dbh = init_dbh %>% add_column(col = 0)
  }
}
colnames(init_dbh) = c("stratum",cols)


#Convert units to cm and ha
for(i in 1:16) {
  strata[[i]] = na.omit(strata[[i]])
  strata[[i]]$dbh_in = as.double(strata[[i]]$dbh_in)
  strata[[i]]$count_acre = as.double(strata[[i]]$count_acre)
  strata[[i]]$dbh_cm = strata[[i]]$dbh_in*in_to_cm
  strata[[i]]$count_ha = strata[[i]]$count_acre*acre_to_ha
}

#Change strata to input format for UVAFME
init_sp_vol1 = init_sp
spec = c("Aspen","Balsam","Birch","Black","White")
for(i in 1:16) {
  temp = as.data.frame(strata[[i]] %>% group_by(species) %>% summarize(sum(count_ha)))
  while(nrow(temp) < 5) { # add missing species as zeroes
    for(j in 1:5) {
      if(!spec[j] %in% temp$species) {
        temp = rbind(temp, c(spec[j], 0.0))
        temp[,2] = as.double(temp[,2])
      }
    }
  }
  temp = temp[order(temp$species),]
  total = sum(temp[,2]) # trees/ha
  perc = temp[,2]/total
  init_sp_vol1 = rbind(init_sp_vol1, c(i, total, 0,0,perc[3],0,perc[5],perc[4],perc[2],perc[1],0,0))
}
init_sp_vol1 = init_sp_vol1[-1,]

init_dbh_vol1 = init_dbh
lbins = c(0,5,10,20,30,40,50,60,70,80)
ubins = c(5,10,20,30,40,50,60,70,80)
dbhbins = matrix(nrow = 5, ncol = 10)
for(i in 1:16) {
  temp = strata[[i]]
  for(j in 1:5) {
    temp1 = temp[temp$species == spec[j],]
    for(k in 1:10) {
      temp2 = temp1[temp1$dbh_cm>lbins[k] & temp1$dbh_cm<ubins[k],]
      dbhbins[j,k] = sum(temp2$count_ha)
    }
  }
  init_dbh_vol1 = rbind(init_dbh_vol1, c(i, rep(0,10), rep(0,10), dbhbins[3,], rep(0,10), dbhbins[5,],
                                             dbhbins[4,], dbhbins[2,], dbhbins[1,], rep(0,10), rep(0,10)))
}
init_dbh_vol1 = init_dbh_vol1[-1,]

#Making up dwarf black spruce params... this is what works nicely in UVAFME
init_sp_vol1 = rbind(init_sp_vol1, c(20,15000,0,0,0,0,0,1,0,0,0,0))
init_dbh_vol1 = rbind(init_dbh_vol1, c(20,rep(0,50),0.98,0.02,rep(0,48)))


#Now volume 2 (Tok)
strata = readRDS(paste0(tempDir, "Inventory_AppB_StemCount_Vol1.RData"))

#Convert units to cm and ha
for(i in 1:16) {
  strata[[i]] = na.omit(strata[[i]])
  strata[[i]]$dbh_in = as.double(strata[[i]]$dbh_in)
  strata[[i]]$count_acre = as.double(strata[[i]]$count_acre)
  strata[[i]]$dbh_cm = strata[[i]]$dbh_in*in_to_cm
  strata[[i]]$count_ha = strata[[i]]$count_acre*acre_to_ha
}

#Change strata to input format for UVAFME
init_sp_vol2 = init_sp
spec = c("Aspen","Balsam","Birch","Black","White")
for(i in 1:16) {
  temp = as.data.frame(strata[[i]] %>% group_by(species) %>% summarize(sum(count_ha)))
  while(nrow(temp) < 5) { # add missing species as zeroes
    for(j in 1:5) {
      if(!spec[j] %in% temp$species) {
        temp = rbind(temp, c(spec[j], 0.0))
        temp[,2] = as.double(temp[,2])
      }
    }
  }
  temp = temp[order(temp$species),]
  total = sum(temp[,2]) # trees/ha
  perc = temp[,2]/total
  init_sp_vol2 = rbind(init_sp_vol2, c(i, total, 0,0,perc[3],0,perc[5],perc[4],perc[2],perc[1],0,0))
}
init_sp_vol2 = init_sp_vol2[-1,]


init_dbh_vol2 = init_dbh
lbins = c(0,5,10,20,30,40,50,60,70,80)
ubins = c(5,10,20,30,40,50,60,70,80)
dbhbins = matrix(nrow = 5, ncol = 10)
for(i in 1:16) {
  temp = strata[[i]]
  for(j in 1:5) {
    temp1 = temp[temp$species == spec[j],]
    for(k in 1:10) {
      temp2 = temp1[temp1$dbh_cm>lbins[k] & temp1$dbh_cm<ubins[k],]
      dbhbins[j,k] = sum(temp2$count_ha)
    }
  }
  init_dbh_vol2 = rbind(init_dbh_vol2, c(i, rep(0,10), rep(0,10), dbhbins[3,], rep(0,10), dbhbins[5,],
                                             dbhbins[4,], dbhbins[2,], dbhbins[1,], rep(0,10), rep(0,10)))
}
init_dbh_vol2 = init_dbh_vol2[-1,]

#Making up dwarf black spruce params... this is what works nicely in UVAFME
init_sp_vol2 = rbind(init_sp_vol2, c(20,5000,0,0,0,0,0,1,0,0,0,0))
init_dbh_vol2 = rbind(init_dbh_vol2, c(20,rep(0,50),0.98,0.02,rep(0,48)))


write.csv(init_sp_vol1, paste0(tempDir, "strata_init_sp_vol1.csv"), quote = F, row.names = F)
write.csv(init_dbh_vol1, paste0(tempDir, "strata_init_dbh_vol1.csv"), quote = F, row.names = F)
write.csv(init_sp_vol2, paste0(tempDir, "strata_init_sp_vol2.csv"), quote = F, row.names = F)
write.csv(init_dbh_vol2, paste0(tempDir, "strata_init_dbh_vol2.csv"), quote = F, row.names = F)
```

